#!/usr/bin/env python3
"""Generate index.json — the whole registry as one file, for anything that reads it over HTTP.

    python scripts/build_index.py            # write index.json
    python scripts/build_index.py --check    # exit 1 if it is out of date (what CI runs)

WHY THIS EXISTS. `data/` is 237 files and `cells/` is 20, which is right for a thing humans edit in
pull requests and wrong for anything fetching it from a browser. A reviewer-facing page that had to
pull 257 files to find twelve candidates would not be a page, it would be a rate limit. So: one
generated file, fetched from raw.githubusercontent.com, regenerated by the same gate that keeps
README.md honest.

It is GENERATED. Do not edit it; edit the entry and re-run. Like README.md, CI fails if the
committed copy disagrees with what the sources produce, which is the only thing that stops a
published page quietly serving last month's list.

Standard library plus pyyaml, like everything else here.
"""
from __future__ import annotations

import json
import sys
from datetime import date, datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("Missing dependency. Install with: pip install pyyaml\n")
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
DATA, CELLS, REVIEWS = ROOT / "data", ROOT / "cells", ROOT / "reviews"
OUT = ROOT / "index.json"

# Exactly the keys a consumer needs. Not the whole entry: `notes` is the longest field in the
# repository and the one most likely to change, and shipping all 237 of them would triple the file
# for a reader that shows one at a time. It is included, because the notes are usually where the
# trap is — but this is the line to revisit if the file ever gets heavy.
KEEP = ("name", "url", "api", "auth", "pillar", "scale", "status", "license", "tags",
        "pilot_relevance", "feeds_cells", "role", "act_kind", "adapter", "added", "updated",
        "description", "notes")


def _j(v):
    """dates are not JSON."""
    return v.isoformat() if isinstance(v, (date, datetime)) else v


def build() -> dict:
    reviews: dict[str, list] = {}
    if REVIEWS.is_dir():
        for p in sorted(REVIEWS.rglob("*.yaml")):
            r = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
            if isinstance(r, dict) and r.get("entry"):
                reviews.setdefault(r["entry"], []).append(
                    {k: _j(r.get(k)) for k in ("by", "org", "date", "territory", "verdict")})

    entries = []
    for p in sorted(DATA.rglob("*.yaml")):
        e = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        rid = p.relative_to(DATA).with_suffix("").as_posix()
        row = {"id": rid, **{k: _j(e.get(k)) for k in KEEP if e.get(k) is not None}}
        row["reviews"] = reviews.get(rid, [])
        entries.append(row)

    cells = []
    for p in sorted(CELLS.glob("*.yaml")):
        c = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        cells.append(c)

    return {
        "generated": date.today().isoformat(),
        "source": "https://github.com/fabcity/awesome-fabcity-data",
        "note": "Generated by scripts/build_index.py. Do not edit; edit data/ or cells/ and re-run.",
        "counts": {"entries": len(entries), "cells": len(cells),
                   "reviews": sum(len(v) for v in reviews.values())},
        "entries": entries,
        "cells": cells,
    }


def main(argv: list[str]) -> int:
    fresh = build()
    text = json.dumps(fresh, indent=1, ensure_ascii=False, sort_keys=False) + "\n"

    if "--check" in argv:
        if not OUT.exists():
            print(f"index.json does not exist. Run: python scripts/build_index.py", file=sys.stderr)
            return 1
        have = json.loads(OUT.read_text(encoding="utf-8"))
        # `generated` is a date and would fail every day for no reason. Everything else must match.
        a, b = dict(have), dict(fresh)
        a.pop("generated", None)
        b.pop("generated", None)
        if a != b:
            print("index.json is out of date. Run: python scripts/build_index.py", file=sys.stderr)
            return 1
        print(f"index.json is current — {fresh['counts']['entries']} entries, "
              f"{fresh['counts']['cells']} cells.")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {fresh['counts']['entries']} entries, "
          f"{fresh['counts']['cells']} cells, {fresh['counts']['reviews']} reviews "
          f"({len(text) // 1024} KB).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
